# Generated by Django 3.0 on 2019-12-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='poll',
            field=models.CharField(max_length=264),
        ),
    ]
