# Generated by Django 3.0 on 2019-12-13 10:46

import contextlib
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20191213_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='poll',
            field=models.ForeignKey(default=contextlib.nullcontext, on_delete=django.db.models.deletion.CASCADE, to='first_app.Poll'),
        ),
    ]
