# Generated by Django 3.0 on 2019-12-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20191213_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='room_num',
            field=models.CharField(default=1, max_length=264),
            preserve_default=False,
        ),
    ]
